Gringotts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('', include('banker.urls', namespace='banker')),
    path('admin/', admin.site.urls),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

banker/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from .views import CustomerListView, CustomerDetailView, TransactionView, TransferView

app_name = 'banker'

urlpatterns = [
    path('', TemplateView.as_view(template_name='banker/index.html'), name='index'),
    path('customer_list/', CustomerListView.as_view(), name='customers'),
    path('customer_list/<pk>/', CustomerDetailView.as_view(), name='customer-detail'),
    path('transactions/', TransactionView.as_view(), name='transaction-history'),
    path('transfer/', TransferView.as_view(), name='transfer'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

banker/models.py
from django.db import models
from datetime import date
from django.utils import timezone

# Create your models here.

class userinfo(models.Model):
    user_img = models.ImageField(upload_to='images/', default='images/profile.jpg')
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    mobile_no = models.IntegerField()
    current_balance = models.IntegerField()
    dob = models.DateTimeField(default=None)
    age = models.IntegerField(default=18)

    def __str__(self):
        return self.name

class TransferInfo(models.Model):
    sender_name = models.CharField(max_length=100)
    reciever_name = models.CharField(max_length=100)
    amount = models.IntegerField()
    date = models.DateField()
    time = models.TimeField()

banker/forms.py
from django import forms

from .models import userinfo

class TransferForm(forms.Form):
    sender_name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(
            attrs={'class':'form-control', 'readonly':True}
        ),
        label='From:'
    )
    reciever_name = forms.ChoiceField(
        choices=userinfo.objects.values_list('id', 'name'),
    )
    # reciever_name = forms.CharField(
    #     max_length=100,
    #     widget=forms.TextInput(
    #         attrs={'class':'form-control'}
    #     ),
    #     label='To:'
    # )
    amount = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={'class':'form-control', 'onkeyup':'check()'}
        ),
        label='Amount:'
    )

    reciever_name.widget.attrs.update({'class':'form-control'})

banker/views.py
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic import View
from django.db import connection

from .models import userinfo, TransferInfo
from .forms import TransferForm

from datetime import date, datetime

# Create your views here.

class CustomerListView(ListView):
    model = userinfo
    template_name = 'banker/view_all_customers.html'
    context_object_name = 'customers'

class CustomerDetailView(DetailView):
    model = userinfo
    template_name = 'banker/customer_info.html'
    context_object_name = 'customer'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TransferForm(initial={'sender_name':kwargs['object']})
        context['users'] = userinfo.objects.all()
        context['bal'] = userinfo.objects.get(pk=7).current_balance
        return context

class TransactionView(ListView):
    model = TransferInfo
    template_name = 'banker/transactions.html'
    context_object_name = 'transactions'

    def get_queryset(self):
        return TransferInfo.objects.order_by('-time')

class TransferView(View):
    def send_money(self, sender, reciever, amt):
        sender_balance = userinfo.objects.raw(f"SELECT id, current_balance FROM banker_userinfo WHERE name='{sender}'")
        reciever_balance = userinfo.objects.raw(f"SELECT id, current_balance FROM banker_userinfo WHERE name='{reciever}'")
        transfer_date = date.today()
        now = datetime.now()
        transfer_time = now.strftime("%H:%M:%S")
        sender_updated_bal = sender_balance[0].current_balance-amt
        reciever_updated_bal = reciever_balance[0].current_balance+amt
        with connection.cursor() as cursor:
            cursor.execute(f"UPDATE banker_userinfo SET current_balance={sender_updated_bal} WHERE name='{sender}'")
            cursor.execute(f"UPDATE banker_userinfo SET current_balance={reciever_updated_bal} WHERE name='{reciever}'")
        a = TransferInfo.objects.create(sender_name=sender, reciever_name=reciever, amount=amt, date=transfer_date, time=transfer_time)
        a.save()

    def get(self, request, *args, **kwargs):
        return render(request, 'banker/view_all_customers.html')

    def post(self, request, *args, **kwargs):
        form = TransferForm(request.POST)
        if form.is_valid():
            sender_name = form.cleaned_data['sender_name']
            reciever_name = form.cleaned_data['reciever_name']
            amt = form.cleaned_data['amount']
            reciever_name = userinfo.objects.get(pk=reciever_name).name
            self.send_money(sender_name, reciever_name, amt)
            return redirect('/customer_list/')

banker/templates/banker/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <link rel="icon" href="{% static 'images/logo.png' %}" type="image/x-icon">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    {% block link %}
    {% endblock %}
</head>

<body>

    <!-- Navbar section -->
    <div style="background-color: #8c02fd;">
        <div class="container">
            <nav class="navbar navbar-expand-lg ">
                <a class="navbar-brand mb-0 h1" href="/">Gringotts</a>
                <button class="navbar-toggler btn-outline-light" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
                </button>

                <div class="collapse home-nav-collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="home-nav-link nav-link" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="customer-nav-link nav-link" href="/customer_list/">Customers</a>
                        </li>
                        <li class="nav-item">
                            <a class="transaction-nav-link nav-link" href="/transactions/">Transactions</a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>

    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

</body>

</html>

banker/templates/banker/customer_info.html
{% extends './base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'css/customer_info.css' %}">
{% endblock %}

{% block content %}
<div class="container">
  <div class="custom-profile">
    <div class="row">
      <div class="col">
        <h4>Customer Profile</h4>
        <span><b>Gringotts-></b><small>Profile</small></span>
      </div>
      <div class="col bal text-center">
        <h6>Available Balance</h6>
        <span style="color: lightgreen;"><b>{{ customer.current_balance }}</b> </span>Galleon
      </div>
    </div>

  </div>

</div>

<div class="container">
  <div class="card mt-4">
    <div class="card-body mt-4">
      <div class="row mt-4">
        <div class="col text-center">
          <img src="{{ customer.user_img.url }}" alt="500" width="100" height="100">
          <p><b>{{ customer.name }}</b></p>
          <small>{{ customer.email }}</small>
        </div>
        <div class="col">
          <table class="table table-striped">
            <tbody>
              <tr>
                <td>Name</td>
                <th>{{ customer.name }}</th>
              </tr>
              <tr>
                <td>Email</td>
                <th>{{ customer.email }}</th>
              </tr>
              <tr>
                <td>Contact</td>
                <th>{{ customer.mobile_no }}</th>
              </tr>
              <tr>
                <td>Date Of Birth</td>
                <th>{{ customer.dob }}</th>
              </tr>
              <tr>
                <td>Age</td>
                <th>{{ customer.age }}</th>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="row mt-4">
        <!-- <button class="btn btn-primary" type="button">Transfer</button> -->
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
          Transfer
        </button>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Transfer Money</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <form action='/transfer/' method="POST" name='transfer_form'>
                  {% csrf_token %}
                  {{ form.as_p }}
                  <input class="btn btn-primary" type="submit" value="Send Money" id="send_btn">
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function check() {
    var amount = document.forms["transfer_form"]["amount"].value;
    if (amount > parseInt('{{ bal }}')) {
      document.getElementById("send_btn").disabled = true;
      document.getElementById("alert").style.display = "block"
    }
    else {
      document.getElementById("send_btn").disabled = false;
      document.getElementById("alert").style.display = "none"
    }
  }
</script>
{% endblock %}

banker/templates/banker/index.html
{% extends './base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6 text-center">
        <img src="{% static 'images/bitcoin.svg' %}" alt="bank vault" width="500" height="500">
    </div>

    <div class="col-md-6 text-center my-auto">
        <h4>Welcome to Gringotts Wizarding Bank. The one and only bank in the world of wizardry, where worlds most
            renowned witches and wizards like to keep their money and valuables. Apart from just keeping their money and
            valueabels, one can also
            transfer money to other fellow witches and wizards.</h4>
        <button class="btn btn-primary mt-4" type="button"><a href="/customer_list/">View All Customers</a></button>
        <button class="btn btn-primary mt-4" type="button"><a href="/transactions/">Transaction History</a></button>
    </div>

</div>
{% endblock %}

banker/templates/banker/transactions.html
{% extends './base.html' %}
{% load static %}

{% block title %}Transaction History{% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'css/transactions.css' %}">
{% endblock %}

{% block content %}
<table class="table table-striped">
    <tbody>
        <thead>
            <tr>
                <th>Sender</th>
                <th>Reciever</th>
                <th>Amount</th>
                <th>Date</th>
                <th>Time</th>
            </tr>
        </thead>
        {% for transaction in transactions %}
            <tr>
                <td>{{ transaction.sender_name }}</td>
                <td>{{ transaction.reciever_name }}</td>
                <td>{{ transaction.amount }}</td>
                <td>{{ transaction.date }}</td>
                <td>{{ transaction.time }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

banker/templates/banker/view_all_customers.html
{% extends './base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block link %}
<link rel="stylesheet" href="{% static 'css/view_all_customers.css' %}">
{% endblock %}

{% block content %}
<div class="container">
  <div class="row mt-4">
    {% for customer in customers %}
    <div class="col-md-4">
      <a class="text-dark" id="info-link" href="{% url 'banker:customer-detail' pk=customer.id %}">
        <div class="card mb-4 box-shadow">
          <div class="card-body">
            <h2 style="font-size:18px;font-weight:bold;min-height:42px;">
              {{ customer.name|truncatechars:50 }}</h2>
            <div class="d-flex justify-content-between align-items-center">
              <small class="text-muted"><b>Email:</b> {{ customer.email }}</small>
              <small class="text-muted"><b>Mobile No:</b> {{ customer.mobile_no }}</small>
            </div>
          </div>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}